# Site
name: "VCS Altkirch"
title: "VCS Altkirch"
description: "Site du Vélo Club Sundgovia Altkirch. Retrouvez toutes les informations du club cycliste : actualités, effectif, résultats, organisations, ..."
meta_description: "Site officiel du Vélo Club Sundgovia Altkirch. Retrouvez toutes les informations du club cycliste : actualités, effectif, résultats, organisations, ..."
logo: 'assets/images/logo-hd.png'
favicon: 'assets/images/favicon.ico'
paginate: 10
url: 'https://vcs-altkirch.fr'
baseurl: '/'
email: 'webmaster-vcsa@ntymail.com'




# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    

# Other
markdown: kramdown
highlighter: rouge

