<!doctype html>

{% extends "index.jj" %}

{% block title %}VCS Altkirch - Contact{% endblock title %}

{% block ifindex %}{% endblock %}
{% block ifcircuits %}class="selected"{% endblock %}


{% block introcontent %}
<h2 class="indexwelcome">Formulaire de contact</h2>
{% endblock introcontent %}

{% block content %}
<form action="https://formspree.io/webmaster-vcsa@ntymail.com"
      method="POST">
	<input type="text" name="_gotcha" style="display:none" />
	
	<p> <label for="nom">Votre nom :</label><br>
    <input type="text" name="name" placeholder="Christopher Froome"> </p>
	<p>
		<label for="nom">Votre adresse mail :</label><br>
		<input type="email"  name="_replyto" placeholder="chrisfroome@teamsky.fr">
	</p>
	<p>
	<label for="nom">Votre message :</label><br>
	<textarea name="message" placeholder="Votre question/remarque ici"></textarea>

	</p>
    <input type="submit" value="Envoyer"><br>
	<p>Après avoir envoyé votre message, vous serez redirigé vers "formspree.io" pour vérifier que vous n'êtes pas un robot, c'est normal !</p>
</form> 
{% endblock content %}