<!doctype html>

{% extends "index.jj" %}

{% block title %}VCS Altkirch - Effectif{% endblock title %}

{% block ifindex %}{% endblock %}
{% block ifeffectif %}class="selected"{% endblock %}


{% block introcontent %}
<h2 class="pagestitle">L'effectif du VCSA </h2>
{% endblock introcontent %}


{% block firstcontent %}
<center><h3> Coureurs </h3></center>
<!-- Note: ne pas mettre de photos de tailles identiques pose souci, merci de travailler les photos en amont (et vive photofiltre/gimp etc)-->
	<!-- première partie -->
	{% for indexCoureurs in range(0,len(listeCoureurs)-1,4) %}
		{% if indexCoureurs%4 == 0 %}
		<table class="coureurs">
		<tr>
			<td><img src="images/coureurs/{{listeCoureurs[indexCoureurs][1]}}.jpg" alt="{{listeCoureurs[indexCoureurs][0]}}" width=80% height=100%></td>
			<td><img src="images/coureurs/{{listeCoureurs[indexCoureurs+1][1]}}.jpg" alt="{{listeCoureurs[indexCoureurs+1][0]}}" width=80% height=100%></td>
			<td><img src="images/coureurs/{{listeCoureurs[indexCoureurs+2][1]}}.jpg" alt="{{listeCoureurs[indexCoureurs+2][0]}}" width=80% height=100%></td>
			<td><img src="images/coureurs/{{listeCoureurs[indexCoureurs+3][1]}}.jpg" alt="{{listeCoureurs[indexCoureurs+3][0]}}" width=80% height=100%></td>
		</tr>
	    <tr>
	    	<td> {{listeCoureurs[indexCoureurs][0]}}<br>{{listeCoureurs[indexCoureurs][2]}}</td>
	    	<td> {{listeCoureurs[indexCoureurs+1][0]}} <br>{{listeCoureurs[indexCoureurs+1][2]}}</td>
			<td> {{listeCoureurs[indexCoureurs+2][0]}} <br>{{listeCoureurs[indexCoureurs+2][2]}}</td>
			<td> {{listeCoureurs[indexCoureurs+3][0]}} <br>{{listeCoureurs[indexCoureurs+3][2]}}</td>
	    </tr>
	    </table>
		{% endif %}
	{% endfor %}
	
	{% set restCoureurs = len(listeCoureurs)%4 %}
	{% if restCoureurs>0 %}
	<table>
	<tr>
		{% for indexDiff in range(restCoureurs) %}
			<td><img src="images/coureurs/{{listeCoureurs[len(listeCoureurs)-restCoureurs+indexDiff][1]}}.jpg" alt="{{listeCoureurs[len(listeCoureurs)-restCoureurs+indexDiff][0]}}" width=80% height=100%></td>
		{% endfor %}
	
	</tr>
	<tr>
		{% for indexDiff in range(restCoureurs) %}
			<td> {{listeCoureurs[len(listeCoureurs)-restCoureurs+indexDiff][0]}} <br>{{listeCoureurs[len(listeCoureurs)-restCoureurs+indexDiff][2]}}</td>
		{% endfor %}
	</table>
	
	<br><br>
	
	<center><h3>Encadrement</h3></center>
	<table>
	<tr>
	<td><img src="images/coureurs/DenisC.jpg"</td>
	<td><img src="images/coureurs/ReneS2.jpg"</td>
	</tr>
	<tr>
	<td>Denis C.<br>Directeur Sportif</td>
	<td>René S.<br>Entraîneur & Directeur Sportif</td>
	</tr>
	</table>
	
	{% endif %}
		<br>
		<p> Un grand merci à <a href="https://www.facebook.com/AurelieTscheillerPhotographiesCyclistes/">Aurélie Tscheiller</a>, <a href="https://www.facebook.com/clichesdinstants/">Au Fil des Instants</a> et <a href="https://www.facebook.com/Tiiffanie-photo-v%C3%A9lo-1692536604344741">Tiiffanie , photo vélo</a> pour les photos.

{% endblock firstcontent %}

{% block nextarticles %}
{% endblock nextarticles%}