<!doctype html>

{% extends "index.jj" %}

{% block title %}VCS Altkirch - Entraînements{% endblock title %}

{% block ifindex %}{% endblock %}
{% block ifentrainements %}class="selected"{% endblock %}


{% block introcontent %}
<img class="cover" src="images/covers/cover_circuits.jpg" width=100%>
{% endblock introcontent %}

{% block content %}
<h2>Les lieux d'entraînements</h2>
		<h4>&#149 Le point de rendez-vous</h4>
		<p> Parking du magasin Sundgau Deux Roues à Altkirch</p>
		<iframe  src="https://www.google.fr/maps/d/embed?mid=1KjQrOzrr8nbzcZf1j3TyMm8ChkY" align=middle width=85% min-width=200 height="200" ></iframe>
		<br>
		<br>
		<h4>&#149 Le circuit du dimanche à Balschwiller (version travaux - août 2017)</h4>
		<iframe src="https://www.google.fr/maps/d/embed?mid=1ELAhfFXgyQcCRbKqJHrQLWGg2OU" align=middle width="85%" min-width=200 height="400" align="middle"></iframe>

		
		{% endblock content %}