<!doctype html>
<html>
<head>
<link href="images/favicon.ico" rel="icon" type="image/x-icon" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>{% block title %}VCS Altkirch{% endblock title %}</title>



<!-- <link rel="apple-touch-icon" sizes="180x180" href="images/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="images/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="images/icons/favicon-16x16.png">
<link rel="manifest" href="images/icons/manifest.json">
<link rel="mask-icon" href="images/icons/safari-pinned-tab.svg" color="#5bbad5"> 
<meta name="theme-color" content="#ffffff"> -->



<link rel="stylesheet" href="css/reset.css" type="text/css" />
<link rel="stylesheet" href="css/styles.css" type="text/css" />
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">


<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/slider.js"></script>
<script type="text/javascript" src="js/superfish.js"></script>

<script type="text/javascript" src="js/custom.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=2, user-scalable=1" />

<!--
deiform, a free CSS web template by ZyPOP (zypopwebtemplates.com/)

Download: http://zypopwebtemplates.com/

License: Creative Commons Attribution
//-->
</head>
<body>
<div id="container" class="width">

	{% block header %}
    <header>
	
	<div class="width">

    		<h1><a href="index.html">VCS Altkirch</a></h1>
	

		<nav>
				
    			<ul class="sf-menu dropdown">
				
				<div class="oncomputer">
				<li {% block ifindex %}class="selected"{% endblock %}><a href="index.html">Accueil</a>
        			<li><a class="oncomputer pasclickable" href="leClub.html">Le Club</a>
        				<ul>
        				<li {% block ifleclub %}{% endblock %}><a href="leClub.html">Le VCSA en bref</a></li>
        				<li {% block ifentrainements %}{% endblock %}><a href="entrainements.html">Entraînements</a></li>
        				<li {% block ifnousrejoindre %}{% endblock %}><a href="nousRejoindre.html">Nous rejoindre</a></li>
						<li {% block ifpartenaires %}{% endblock %}><a href="partenaires.html">Nos partenaires</a></li>
        				</ul>
        			</li>
	     			<li {% block iforganisations %}{% endblock %}><a href="organisations.html">Nos organisations</a></li>
					<li><a class="pasclickable" href="#">Saison 2017</a>
						<ul>
						<li {% block ifcoureurs %}{% endblock %}><a href="coureurs.html">Les coureurs</a></li>
						<li {% block ifresultats %}{% endblock %}><a href="resultats.html">Les résultats</a></li>
						</ul>
					</li>
					<li><a  href=http://veloclubaltkirch.xoo.it/index.php>Forum</a></li>
				</div>
				
				
				<div class="onmobile">
				<li><a class="pasclickable" href="#">MENU</a>
				
					<ul>
			
        			<li {{ self.ifindex() }}}><a href="index.html">Accueil</a>
        			<li><a class="pasclickable" href="leClub.html">Le Club</a>
        				<ul>
        				<li {{ self.ifleclub() }}><a href="leClub.html">Le VCSA en bref</a></li>
        				<li {{ self.ifentrainements() }}><a href="entrainements.html">Entraînements</a></li>
        				<li {{ self.ifnousrejoindre() }}><a href="nousRejoindre.html">Nous rejoindre</a></li>
						<li {{ self.ifpartenaires() }}><a href="partenaires.html">Nos partenaires</a></li>
        				</ul>
        			</li>
	     			<li {{ self.iforganisations() }}><a href="organisations.html">Nos organisations</a></li>
					<li><a class="pasclickable" href="#">Saison 2017</a>
						<ul>
						<li {{ self.ifcoureurs() }}><a href="coureurs.html">Les coureurs</a></li>
						<li {{ self.ifresultats() }}><a href="resultats.html">Les résultats</a></li>
						</ul>
					</li>
					<li><a href=http://veloclubaltkirch.xoo.it/index.php>Forum</a></li>
				
       			</ul>
				</ul>
				</li>
			</div>
			
			<div class="clear"></div>
    		</nav>
       	</div>

	<div class="clear"></div>

      
    </header>
	{% endblock header %}

	
    <div id="intro">

	<div class="width">
			
				<div class="intro-content">
					{% block introcontent %}
						<img class="logo" src="images/logo.png" style="float: right" >
						<img class="logo" src="images/logo.png" style="float: left;" >
						<h2 class="indexwelcome">Bienvenue sur le site du </br> VC Sundgovia Altkirch ! </h2>
					{% endblock introcontent %}
            	</div> <!-- intro content-->
                
            </div> <!-- width -->
            

	</div> <!--  intro-->

    <div id="body" class="width">
		
		<section id="content" class="two-column with-right-sidebar">
		{% block content %}
	    <article>
		<h3>Dernières nouvelles</h3>
		<hr>
		<br>
		<h4>Antoine Mattern vainqueur du GP de la MJC à Buhl en Pass' Cyclisme!</h4>
			<div class="article-info">Rédigé le 15 août</div> 
			<p> Après de nombreuses places d'honneur cette année, Antoine est ce mardi monté pour la première fois sur la plus haute marche du podium à Buhl. Une victoire en solitaire avec plus de 3 minutes d'avance sur ses poursuivants ! </p>
			<center><img src="images/AntoineBuhl.jpg" width=50%></center>
		</p>
		<br>
		<h4>Hugo sélectionné aux championnats d'Europe au Danemark!</h4>
			<div class="article-info">Rédigé le 25 Juillet</div>
			<p> Après plusieurs sélections en Equipe de France Espoirs, Hugo va vivre le dimanche 6 août sa première course sous les couleurs de l'équipe de France élites ! Sélectionné avec 8 autres coureurs par Cyrille Guimard, il épaulera Bryan Coquard.</p>
		</p>
		</article>
		{% endblock content %}
        </section>
        
		
		{% block rightsidebar %}
        <!-- barre de droite -->
        <aside class="sidebar right-sidebar">
		
		<ul>	
					
			<ul>
            <li>
				<h4><a href="performances.html">Bilan 2017</a></h4>
				<ul class="topranks">
				<li>
					<p><span class="topranks-type">{{bilan[0]}} Victoires</span> <span class="serre">({{bilan[1]}}&nbsp;en&nbspFSGT,&nbsp;{{bilan[2]}}&nbsp;en&nbsp;FFC)</span></p>
				</li>
				<li>
					<p><span class="topranks-type">{{bilan[3]}} Podiums</span> </span> <span class="serre">({{bilan[4]}}&nbsp;en&nbsp;FSGT,&nbsp;{{bilan[5]}}&nbsp;en&nbsp;FFC)</span></p>
				</li>
				<li>
					<p><span class="topranks-type">{{bilan[6]}} Top 10</span></p>
				</li>
			</ul>
            <li>
                <h4>Revue de presse</h4>
               	<ul>
					<li>11/08/17: <a href="http://www.sport365.fr/cyclisme-arctic-race-e2-kristoff-brise-reve-dhofstetter-5205220.html">Kristoff brise le rêve d'Hofstetter</a> (sport365)</li>
					<li>24/07/17: <a href="http://www.lalsace.fr/actualite/2017/07/24/hofstetter-a-l-euro">Hofstetter à l'Euro</a> (L'Alsace)</li>
               		<li>20/07/17: <a href="http://www.radiopeloton.fr/2017/07/20/kohler-sans-pitie-pour-les-franciliens/">Kohler sans pitié pour les franciliens</a> (Radio Peloton)</li>					
					<li>24/04/17: <a href="http://www.lalsace.fr/sport/2017/04/24/la-premiere-pour-grimont">La première pour Grimont</a> (L'Alsace)</li>
					<li>20/03/17: <a href="http://www.lalsace.fr/sport/2017/03/20/heinis-au-bonheur-du-vcs-altkirch">Heinis au bonheur du VCS Altkirch</a> (L'Alsace)</li>					
					<li>17/03/17: <a href="http://www.dna.fr/edition-de-saint-louis-altkirch/2017/03/17/le-vcs-altkirch-bien-represente">Le VCS Altkirch bien représenté</a> (DNA)</li>	
					<li>28/12/16: <a href="http://www.dna.fr/edition-de-saint-louis-altkirch/2016/12/28/1-800-pour-le-vcs-altkirch">1800€ pour le VCS Altkirch</a> (DNA)</li>
					<li>30/09/16: <a href="http://www.lalsace.fr/sport/2016/11/30/l-effet-hofstetter-au-vcs-altkirch">L'effet Hofstetter au VCS Altkirch</a> (L'Alsace)</li>
					<li>02/06/16: <a href="http://www.lalsace.fr/sport/2016/06/02/l-union-sacree-au-vcs-altkirch">L'union sacrée au VCS Altkirch</a> (L'Alsace)</li>
				</ul>
            </ul>    
            </li>

            <ul>	
            <li>
            <h4>Liens utiles</h4>
            <ul class="blocklist">
				<li><a href="http://fsgt-cyclisme-alsace.shost.ca/index.html">FSGT Cyclisme Alsace</a></li>
				<li><a href="http://grandestcyclisme.fr/">FFC Grand Est</a></li>
				<li><a href="http://ffc-bfc.fr">FFC Bourgogne Franche-Comté</a></li>
				<li><a href="http://rad-net.de">Fédération Allemande</a></li>
				<li><a href="http://swiss-cycling.ch/fr.html">Fédération Suisse</a></li>
				<li><a href="http://www.meteofrance.com/previsions-meteo-france/altkirch/68130">Météo Altkirch</a></li>	
			</ul>
            
		</ul>   
        </ul>
		
		
        </aside>
		{% endblock rightsidebar %}
    	<div class="clear"></div>
    </div>
</div>

	<!-- pied de page -->
	{% block footer %}
    <footer>
	
	<div class="footer-content">
		<table>
		<tr>
        <td><a href="http://www.as-bike.fr/"><img src="images/sponsors/ASBike.jpg" alt="AS Bike"></a></td>
		<td><a href="http://www.idfermetures.fr/"><img src="images/sponsors/IDFermetures.jpg" alt="ID Fermetures"></a></td>
		<td><a href="http://annuaire.cci.alsace/fr/entreprise/ANTONIO-CACCESE-ELECTRICITE-INDUSTRIELLE-ACEI.html?PHPSESSID=5fe55720be92351d90798fb0e0e25e00"><img src="images/sponsors/AceiElectricite.jpg" alt="ACEI Electricité"></a></td>	
		<td><img src="images/sponsors/LBprotheses.jpg" alt="LBprotheses"></td>
		</tr>
		</table>
        <table>
		<tr> 
		<td><a href="https://www.daiichi-sankyo.fr/"><img src="images/sponsors/DaiichiSankyo.jpg" alt="Daiichi Sankyo"></a></td>
		<td><img href="https://www.pagesjaunes.fr/pros/52105117" src="images/sponsors/MarcBoetsch.jpg" alt="Marc Boetsch"></td>
		<td><a href="http://arcade-engineering.com//"><img src="images/sponsors/Arcade.jpg" alt="Arcade Engineering"></a></td>
		<td><a href="http://www.cordonnerie-riedisheim.fr/fr"><img src="images/sponsors/CordonnerieRiedisheim.jpg" alt="Cordonnerie Riedisheim"></a></td>
		<td><img src="images/sponsors/BoucherieSchmidlin.jpg" alt="Boucherie Schmidlin"></td>
		</tr>
		</table>
		<table>
		<tr> 
		<td><a href="https://www.creditmutuel.fr"><img src="images/sponsors/CreditMutuel.jpg" alt="Crédit Mutuel"></a></td>
		<td><a href="http://www.mairie-altkirch.fr/"><img src="images/sponsors/Altkirch.png" alt="Ville d'Altkirch"></a></td>
		<td><a href="http://www.fun2sport.fr/"><img src="images/sponsors/Fun2Sport.png" alt="Fun2Sport"></a></td>
		</table>
        		
        <div class="clear"></div>
        </div>
        <div class="footer-bottom">
            <p>&copy; VCS Altkirch 2017. Template: <a href="http://zypopwebtemplates.com/">Free CSS Web Templates</a> par ZyPOP. Site personnalisé par Florian. <a href="contact.html">Contact</a>
         </div>
	
    </footer>
	{% endblock footer %}
</body>
</html>
