<!doctype html>
<html>
<head>
<link href="images/favicon.ico" rel="icon" type="image/x-icon" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>{% block title %}VCS Altkirch{% endblock title %}</title>

<link rel="stylesheet" href="css/reset.css" type="text/css" />
<link rel="stylesheet" href="css/styles.css" type="text/css" />
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">


<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/slider.js"></script>
<script type="text/javascript" src="js/superfish.js"></script>

<script type="text/javascript" src="js/custom.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=2, user-scalable=1" />

<!--
deiform, a free CSS web template by ZyPOP (zypopwebtemplates.com/)

Download: http://zypopwebtemplates.com/

License: Creative Commons Attribution
//-->
</head>
<body>
<div id="container" class="width">

	{% block header %}
    <header>
	
	<div class="width">

    		<h1><a href="index.html">VCS Altkirch</a></h1>
	

		<nav>
				
    			<ul class="sf-menu dropdown">
				
				<div class="oncomputer">
				<li {% block ifindex %}class="selected"{% endblock %}><a href="index.html">Accueil</a>
        			<li><a class="oncomputer pasclickable" href="leClub.html">Le Club</a>
        				<ul>
        				<li {% block ifleclub %}{% endblock %}><a href="leClub.html">Le VCSA en bref</a></li>
        				<li {% block ifcircuits %}{% endblock %}><a href="circuits.html">Circuits d'entraînement</a></li>
        				<li {% block ifnousrejoindre %}{% endblock %}><a href="nousRejoindre.html">Nous rejoindre</a></li>
						<li {% block ifpartenaires %}{% endblock %}><a href="partenaires.html">Nos partenaires</a></li>
        				</ul>
        			</li>
	     			<li {% block iforganisations %}{% endblock %}><a href="organisations.html">Nos organisations</a></li>
					<li><a class="pasclickable" href="#">Saison 2017</a>
						<ul>
						<li {% block ifcoureurs %}{% endblock %}><a href="coureurs.html">Les coureurs</a></li>
						<li {% block ifresultats %}{% endblock %}><a href="resultats.html">Les résultats</a></li>
						</ul>
					</li>
					<li><a  href=http://veloclubaltkirch.xoo.it/index.php>Forum</a></li>
				</div>
				
				
				<div class="onmobile">
				<li><a class="pasclickable" href="#">MENU</a>
				
					<ul>
			
        			<li {{ self.ifindex() }}}><a href="index.html">Accueil</a>
        			<li><a class="pasclickable" href="leClub.html">Le Club</a>
        				<ul>
        				<li {{ self.ifleclub() }}><a href="leClub.html">Le VCSA en bref</a></li>
        				<li {{ self.ifcircuits() }}><a href="circuits.html">Circuits d'entraînement</a></li>
        				<li {{ self.ifnousrejoindre() }}><a href="nousRejoindre.html">Nous rejoindre</a></li>
						<li {{ self.ifpartenaires() }}><a href="partenaires.html">Nos partenaires</a></li>
        				</ul>
        			</li>
	     			<li {{ self.iforganisations() }}><a href="organisations.html">Nos organisations</a></li>
					<li><a class="pasclickable" href="#">Saison 2017</a>
						<ul>
						<li {{ self.ifcoureurs() }}><a href="coureurs.html">Les coureurs</a></li>
						<li {{ self.ifresultats() }}><a href="resultats.html">Les résultats</a></li>
						</ul>
					</li>
					<li><a href=http://veloclubaltkirch.xoo.it/index.php>Forum</a></li>
				
       			</ul>
				</ul>
				</li>
			</div>
			
			<div class="clear"></div>
    		</nav>
       	</div>

	<div class="clear"></div>

      
    </header>
	{% endblock header %}

	
    <div id="intro">

	<div class="width">
      
		<div class="intro-content">
					{% block introcontent %}<img class="logo" src="images/logo.png" height = 100 width = 80 style="float: right;" >
					<img class="logo" src="images/logo.png" height = 100 width = 80 style="float: left;" >
                    <h2 class="indexwelcome">Bienvenue sur le site du </br> VC Sundgovia Altkirch ! </h2>
                    {% endblock introcontent %}

            	</div> <!-- intro content-->
                
            </div> <!-- width -->
            

	</div> <!--  intro-->

    <div id="body" class="width">
		
		<section id="content" class="two-column with-right-sidebar">
		{% block content %}
	    <article>
				
		<h3>Le mot du Président</h3>
		
		<p> "Bonjour, vive le vélo club Sundgovia Altkirch, vive le vélo en sécurité sur les routes, je vous souhaite une excellente année pleine de réussite et je vous donne rendez-vous à Seppois-le-bas pour l'ouverture de la saison FSGT. Sportivement."<br> G.H</p>
		
		<br>
		<td><img src="images/vcsa.jpg"></td>
			
		<p>
		<h3>Dernières nouvelles</h3>
		<hr>
		<br>
		<h4>Antoine M. vainqueur du GP de la MJC à Buhl en Pass' Cyclisme!</h4>
			<div class="article-info">Rédigé le 15 août</div> 
			<p> Après de nombreuses places d'honneur cette année, Antoine est ce mardi monté pour la première fois sur la plus haute marche du podium à Buhl, à l'issue d'une victoire en solitaire. </p>
			<center><img src="images/AntoineBuhl.jpg" width=50%></center>
		</p>
		<br>
		<h4>Hugo sélectionné aux championnats d'Europe au Danemark!</h4>
			<div class="article-info">Rédigé le 25 Juillet</div>
			<p> Après plusieurs sélections en Equipe de France Espoirs, Hugo va vivre le dimanche 6 août sa première course sous les couleurs de l'équipe de France élites ! Sélectionné avec 8 autres coureurs par Cyrille Guimard, il épaulera Bryan Coquard.</p>
		</p>
		</article>
		{% endblock content %}
        </section>
        
		
		{% block rightsidebar %}
        <!-- barre de droite -->
        <aside class="sidebar right-sidebar">
		
		<ul>	
					
			<ul>
            <li>
				<h4><a href="performances.html">Bilan 2017</a></h4>
				<ul class="topranks">
				<li>
					<p><span class="topranks-type">{{bilan[0]}} Victoires</span> ({{bilan[1]}} en FSGT, {{bilan[2]}} en FFC)</p>
				</li>
				<li>
					<p><span class="topranks-type">{{bilan[3]}} Podiums</span> ({{bilan[4]}} en FSGT, {{bilan[5]}} en FFC) </p>
				</li>
				<li>
					<p><span class="topranks-type">{{bilan[6]}} Top 10</span></p>
				</li>
			</ul>
            <li>
                <h4>Revue de presse</h4>
               	<ul>
					<li>11/08/17: <a href="http://www.sport365.fr/cyclisme-arctic-race-e2-kristoff-brise-reve-dhofstetter-5205220.html">Kristoff brise le rêve d'Hofstetter</a> (sport365)</li>
					<li>24/07/17: <a href="http://www.lalsace.fr/actualite/2017/07/24/hofstetter-a-l-euro">Hofstetter à l'Euro</a> (L'Alsace)</li>
               		<li>20/07/17: <a href="http://www.radiopeloton.fr/2017/07/20/kohler-sans-pitie-pour-les-franciliens/">Kohler sans pitié pour les franciliens</a> (Radio Peloton)</li>					
					<li>24/04/17: <a href="http://www.lalsace.fr/sport/2017/04/24/la-premiere-pour-grimont">La première pour Grimont</a> (L'Alsace)</li>
					<li>20/03/17: <a href="http://www.lalsace.fr/sport/2017/03/20/heinis-au-bonheur-du-vcs-altkirch">Heinis au bonheur du VCS Altkirch</a> (L'Alsace)</li>					
					<li>17/03/17: <a href="http://www.dna.fr/edition-de-saint-louis-altkirch/2017/03/17/le-vcs-altkirch-bien-represente">Le VCS Altkirch bien représenté</a> (DNA)</li>	
					<li>28/12/16: <a href="http://www.dna.fr/edition-de-saint-louis-altkirch/2016/12/28/1-800-pour-le-vcs-altkirch">1800€ pour le VCS Altkirch</a> (DNA)</li>
					<li>30/09/16: <a href="http://www.lalsace.fr/sport/2016/11/30/l-effet-hofstetter-au-vcs-altkirch">L'effet Hofstetter au VCS Altkirch</a> (L'Alsace)</li>
<li>02/06/16: <a href="http://www.lalsace.fr/sport/2016/06/02/l-union-sacree-au-vcs-altkirch">L'union sacrée au VCS Altkirch</a> (L'Alsace)</li>
				</ul>
            </ul>    
            </li>

            <ul>	
            <li>
            <h4>Liens utiles</h4>
            <ul class="blocklist">
				<li><a href="http://fsgt-cyclisme-alsace.shost.ca/index.html">FSGT Cyclisme Alsace</a></li>
				<li><a href="http://grandestcyclisme.fr/">FFC Grand Est</a></li>
				<li><a href="http://ffc-bfc.fr">FFC Bourgogne Franche-Comté</a></li>
				<li><a href="http://rad-net.de">Fédération Allemande</a></li>
				<li><a href="http://swiss-cycling.ch/fr.html">Fédération Suisse</a></li>
				<li><a href="http://lalsace.fr">L'Alsace</a></li>					<li><a href="http://dna.fr">DNA</a></li>	
			</ul>
            
		</ul>   
        </ul>
		
		
        </aside>
		{% endblock rightsidebar %}
    	<div class="clear"></div>
    </div>
</div>

	<!-- pied de page -->
	{% block footer %}
    <footer>
	
	<div class="footer-content width">
		<table>
		<tr>
        <td><img src="images/sponsors/ASBike.jpg" alt="AS Bike"></td>
		<td><img src="images/sponsors/IDFermetures.jpg" alt="ID Fermetures"></ul></td>
		<td><img src="images/sponsors/SundgauDeuxRoues.jpg" alt="Sundgau Deux Roues"></td>
		<td><img src="images/sponsors/MaisonsSwissBois.jpg" alt="Maisons Swiss Bois"></td>
		</tr>
		</table>
          		<table>
		<tr>  
		<td><img src="images/sponsors/CreditMutuel.jpg" alt="Crédit Mutuel"></td>
		<td><img src="images/sponsors/Fun2Sport.png" alt="Fun2Sport"></td>
		<td><img src="images/sponsors/DaiichiSankyo.jpg" alt="Daiichi Sankyo"></td>
		<td><img src="images/sponsors/Altkirch.png" alt="Crédit Mutuel"></td>
		</tr>
		</table>
            
        <div class="clear"></div>
        </div>
        <div class="footer-bottom">
            <p>&copy; VCS Altkirch 2017. Template: <a href="http://zypopwebtemplates.com/">Free CSS Web Templates</a> par ZyPOP. Site personnalisé par Florian.</p>
         </div>
	
    </footer>
	{% endblock footer %}
</body>
</html>
