<!doctype html>

{% extends "index.jj" %}

{% block title %}VCS Altkirch - Partenaires{% endblock title %}

{% block ifindex %}{% endblock %}
{% block ifpartenaires %}class="selected"{% endblock %}


{% block introcontent %}
<img class="cover" src="images/covers/cover_partenaires.jpg" width=100%>
{% endblock introcontent %}

{% block content %}
<h2>Les partenaires du VCSA </h2>
<p> Le  VCS Altkirch ne serait rien sans ses partenaires et les remercie particulièrement pour leur soutien. Notamment : </p>

<h4>&#149 ACEI Électricité</h4>
<p>Antonio Caccese électricité industrielle - Travaux d'installation électrique, de dépannage et de mise aux normes électriques entre autres.<br>
Basé à Waldighoffen.</p>	

<h4>&#149 Arcade Engineering GmbH</h4>
<p>Votre partenaire expérimenté pour des prestations d'ingénierie et pour la planification de projets d'équipements industriels.<br>
=> Plus d'infos sur le <a href="http://arcade-engineering.com/Accueil.html">site de Arcade Engineering</a>.</p>

<h4>&#149 AS Bike</h4>
<p> Spécialiste vélo & triathlon à Rixheim.<br>
   => Plus d'infos sur le <a href="http://www.as-bike.fr">site de AS Bikes</a> ou sur la <a href="https://www.facebook.com/asbike.rixheim">page Facebook</a>.</p>

<h4>&#149 Boucherie Schmidlin</h4>
<p>Boucherie - Charcuterie - Traiteur à Altkirch depuis 1977.</p>

<h4>&#149 Cordonnerie de Riedisheim</h4>
<p>Cordonnerie haut de gamme dans le Haut-Rhin, restauration et entretien de vos chausssures.<br>Vente de produits d'entretien et rayon clés service.<br>
  => Plus d'infos sur le <a href="http://www.cordonnerie-riedisheim.fr/fr">site de la cordonnerie de Riedisheim</a>.</p>

<h4>&#149 Le Crédit Mutuel</h4>
<p> Banque coopérative, propose également des assurances, forfaits téléphoniques, etc.<br>
=> Plus d'infos sur le <a href="http://www.credit-mutuel.fr">site du Crédit Mutuel</a>.</p>   

<h4>&#149 Daiichi Sankyo</h4>
<p> Entreprise pharmaceutique.<br>
   => Plus d'infos sur le <a href="http://www.daiichi-sankyo.fr">site de Daiichi Sankyo</a></p>

<h4>&#149 Fun2Sport</h4>
<p> Vos Vacances & Stages Vélo sous toutes les formes, souvent avec d'anciens Coureurs Pro et toujours avec du plaisir, de la convivialité et du Fun!<br>
=> Plus d'infos sur le <a href="http://www.fun2sport.fr/">site de Fun2Sport</a> ou sur la <a href="https://www.facebook.com/alain.lamy.fun2sport.fr/">page Facebook</a>.</p>   
	    
<h4>&#149 ID Fermetures</h4>
<p>Basée à Ilzach, l'entreprise ID Fermetures vous propose la fourniture et la pose de :<br>
Fenêtres - Portes d'entrée / de service / blindées - Volets roulants / volets battants<br>
Portes de garage - Stores (bannes, pergolas, etc.) - Portails / garde-corps / clôtures<br>
  => Plus d'infos sur le <a href="http://www.idfermetures.fr">site de ID Fermetures ou sur la <a href="http://www.facebook.com/IDFermetures">page Facebook</a>.</p>
  
<h4>&#149 LB Prothèses Dentaires</h4>
<p> Prothésistes dentaires à Altkirch depuis 2002.<br></p>

<h4>&#149 Marc Boetsch</h4>
<p>Entreprise de menuiseries métalliques à Altkirch.</p>
	    
<p> Merci également à la <a href="http://www.mairie-altkirch.fr">ville d'Altkirch</a> pour son soutien !</p>
{% endblock content %}