<!doctype html>

{% extends "index.jj" %}

{% block title %}VCS Altkirch - Résultats{% endblock title %}

{% block ifindex %}{% endblock %}
{% block ifresultats %}class="selected"{% endblock %}


{% block introcontent %}
<img class="cover" src="images/covers/cover_resultats.jpg" width=100%>
{% endblock introcontent %}

{% block content %}
<h2>Les résultats des coureurs du VCSA </h2>
		<h4>&#149 15 août</h4>
		<h5>Prix de la MJC à Buhl:</h5>
		<p> <ul><li>Victoire de Antoine M. en Pass' Cyclisme!</li></ul></p>
		
	    <h4>&#149 19 juillet</h4>
		<h5>Montgeron (Essonne):</h5>
		<p> <ul><li>Victoire de Florian K. en 3-J !</li></ul></p>
		
		<h4>&#149 25 juin</h4>
		<h5>L'Alsacienne Cyclosportive : </hr>
		<p> <ul><li>Julien B. 3ème sur l'Audacieuse</li></ul></p>
		<h5> GP de Danjoutin (FSGT) :</hr>
		<p><ul><li> Mathieu N. 2ème en 2/3</li></ul></p>
		
		<h4>&#149 4 juin</h4>
		<h5>GP de Bourogne (FSGT):</h5>
		<p> <ul>
			<li>Jérôme J. 2ème (V4)</li>
			<li>Anthony W. 2ème (Cadets)</li>
		</ul></p>
		
		<h4>&#149 20-21 mai</h4>
		<h5>Tour du Territoire de Belfort :</hr>
		<p><ul>
			<li> L'équipe 4ème sur 29 au contre-la-montre par équipe</li>
			<li> Julien G. 3ème de la 3ème étape et 2ème du classement général !</li>
		</ul> </p>
		
		<h4>&#149 1er mai</h4>
		<h5>Prix PTM Soft :</hr>
		<p><ul><li> Jérôme H. Champion du Haut-Rhin Juniors !</li></ul> </p>
		
		<h4>&#149  23 avril</h4>
		<h5>Montreux-Vieux (FSGT) :</h5>
		<p><ul><li> Victoire de Julien.G en 2-3 !</li>
		<li> Doublé des frères Schlienger en V4 !</li></ul></p>
{% endblock content %}